version: "3"
services:
  app:
    build: ./app
    container_name: app
    ports:
      - "3030:3030"
    links:
      - pgdb
    depends_on:
      - pgdb
    environment:
      - PG_SSLMODE=disable
      - PG_PORT=5432
      - PG_HOST=pgdb
      - PG_DBNAME=test
      - PG_USER=postgres
      - PG_PASSWORD=password
    volumes:
      - ./app:/app
      - ./app/files:/app/files:Z
    command: air

  pgdb:
    image: postgres:12.5
    container_name: pgdb
    ports:
      - "5432:5432"
    volumes:
      - ./pg-data:/var/lib/postgresql/data:Z
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test
