version: "3"
services:
  app:
    build: ./app
    container_name: app
    ports:
      - "3030:3030"
    links:
      - mydb
      - pgdb
    depends_on:
      - mydb
      - pgdb
    environment:
      - PG_SSLMODE=disable
      - PG_PORT=5432
      - PG_HOST=pgdb
      - PG_DBNAME=test
      - PG_USER=postgres
      - PG_PASSWORD=password
    volumes:
      - ./app:/app
    command: air

  mydb:
    build: ./mysql
    container_name: mydb
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: hoge
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./mysql/db:/var/lib/mysql

  pgdb:
    image: postgres:12.5
    container_name: pgdb
    ports:
      - "5432:5432"
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test
